test:
  name: TestName
  value: Value

greeting:
  message: hello
quarkus:
  swagger-ui:
    always-include: true
  application:
    name: getting-started


"%dev":
  quarkus:
    http:
      port: 8080

# mvn -Dquarkus-profile=stage compile quarkus:dev
"%stage":
  quarkus:
    http:
      port: 8080

"%prod":
  quarkus:
    http:
      port: 8181